accounts/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include
from . import views

app_name = 'accounts'
urlpatterns = [
    #include default auth urls
    path('', include('django.contrib.auth.urls')),
    #registration page
    path('register/', views.register, name='register'),
    # User profile page
    path('my-profile/', views.profile, name='profile'),
]

blog/urls.py
from django.urls import path, include

from . import views

app_name = 'blog'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),

    # All posts page
    path('posts/', views.BlogPostListView.as_view(), name='posts'),

    # All bloggers page
    path('bloggers/', views.UserListView.as_view(), name='bloggers'),

    # Post detail page
    path('post/<int:pk>/<slug:title>/', views.post_detail, name='post-detail'),

    # Blogger detail page
    path('blogger/<str:username>/', views.blogger_detail, name='blogger-detail'),

    # New post
    path('post/new', views.new_post, name='new-post'),

    # New Comment
    path('comment/new/<int:pk>/', views.new_comment, name='new-comment'),

    # Blog post edit
    path('post/<int:pk>/edit', views.edit_post, name='edit-post'),

    # Blog post delete
    path('post/<int:pk>/delete', views.BlogPostDelete.as_view(), name='delete-post'),
]

microblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # Blog app
    path('', include('blog.urls')),

    # Registration & Authentication
    path('accounts/', include('accounts.urls')),

    # Admin
    path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from microblog.settings import AUTH_USER_MODEL
from django.template.defaultfilters import slugify
from datetime import datetime, timedelta
from django.utils import timezone

# Create your models here.
class BlogPost(models.Model):
    """Model representing a blog post"""
    title = models.CharField(max_length=200, help_text="Enter a Title (Max 200 characters)")
    # Auto date add
    date_added = models.DateTimeField(auto_now_add=True, editable=False)
    # Foreign key to blogger - post can only belong to a blogger but a blogger can have multiple posts
    blogger = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    # Post content
    content = models.TextField(help_text="Enter your post here.")
    # Public content displayed outside your profile?
    private = models.BooleanField(default=False)
    # Slug for URLs
    slug = models.SlugField(default='', editable=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        """Returns the url to access a detail view for this post"""
        return reverse('blog:post-detail', args=[self.pk,str(self.slug)])

    def is_new(self):
        """Determine if a post is new enough to get the New badge in sidebar"""
        return self.date_added > (timezone.now() - timedelta(days=1))

    def __str__(self):
        """Return a string representing BlogPost"""
        return f'{self.title} - {self.blogger.username}'

class Comment(models.Model):
    """Model representing a comment on a blog post"""
    # Auto date time add
    date_added = models.DateTimeField(auto_now_add=True, editable=False)
    # Foreign key to blog post - comment can only belong to a post but a post can have multiple comments
    post = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
    # Comment content
    comment = models.TextField(help_text='Enter your comment here.')
    # Comment owner - foreign key to user
    owner = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string of post title and username"""
        return f'Comment for "{self.post.title}" by {self.owner.username}'

blog/forms.py
from django import forms
from .models import BlogPost, Comment
from ckeditor.widgets import CKEditorWidget
from django_bleach.forms import BleachField

class PostForm(forms.ModelForm):
    content = BleachField(widget=CKEditorWidget())
    class Meta:
        model = BlogPost
        fields = ['title', 'content', 'private']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['comment'].label = ""

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404, Http404
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import get_user_model
from django.urls import reverse, reverse_lazy
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import random

from blog.models import BlogPost, Comment
from .forms import PostForm, CommentForm

# Get custom user model
User = get_user_model()

def check_post_owner(post, request):
    """Ensure request user owns the post"""
    if post.blogger != request.user:
        raise Http404

# Create your views here.
def index(request):
    posts = BlogPost.objects.filter(private=False)
    random_post = random.choice(posts)
    context = {
        'post': random_post
    }
    return render(request, 'blog/index.html', context=context)

class BlogPostListView(generic.ListView):
    """Generic list view for blog posts"""
    model = BlogPost
    paginate_by = 5

    def get_queryset(self):
        return BlogPost.objects.filter(private=False).order_by('-date_added')

class UserListView(generic.ListView):
    """General list view for all bloggers"""
    model = User
    paginate_by = 25

    def get_queryset(self):
        return User.objects.order_by('last_name')

def post_detail(request, pk, title):
    """Retrieves details for a specific post."""
    post = get_object_or_404(BlogPost, pk=pk)
    form = CommentForm()
    comments = post.comment_set.order_by('-date_added')
    page = request.GET.get('page', 1)
    paginator = Paginator(comments, 5)
    try:
        comments = paginator.page(page)
    except PageNotAnInteger:
        comments = paginator.page(1)
    except EmptyPage:
        comments = paginator.page(paginator.num_pages)

    # Check if post is private, if it is, and the request user != the owner of the post, redirect to 404. Otherwise render template.
    if post.private and request.user != post.blogger:
        raise Http404
    else:
        context = {
            'post': post,
            'form': form,
            'comments': comments,
        }
        return render(request, 'blog/post_detail.html', context=context)

# Retrieves blogger detail page, note that username is used in the url config rather than pk/id
def blogger_detail(request, username):
    """Retrieves details for a blogger detail page"""
    blogger = get_object_or_404(User, username=username)
    posts = BlogPost.objects.filter(blogger=blogger.pk).order_by('-date_added')[:5]
    context = {
        'blogger': blogger,
        'posts': posts,
    }
    return render(request, 'blog/blogger_detail.html', context=context)

# New Post
@login_required
def new_post(request):
    """Add a new blog post"""
    if request.method != 'POST':
        # No data submitted, create blank form
        form = PostForm()
    else: 
        # POST data submitted, process form
        form = PostForm(data=request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.blogger = request.user
            new_post.save()
            return redirect('blog:post-detail', new_post.pk, new_post.slug)

    # Display blank or invalid form
    context = {'form': form}
    return render(request, 'blog/new_post.html', context)

@login_required
def new_comment(request, pk):
    """Add a new comment to a BlogPost"""
    post = BlogPost.objects.get(pk=pk)
    if request.method == 'POST':
        # Data submitted, process form
        form = CommentForm(data=request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.owner = request.user
            new_comment.post = post
            new_comment.save()
            return redirect('blog:post-detail', post.pk, post.slug)
    else:
        return Http404

@login_required
def edit_post(request, pk):
    """Edit an existing entry"""
    post = get_object_or_404(BlogPost, pk=pk)
    check_post_owner(post, request)

    if request.method != 'POST':
        #Intial request, pre-fill form with current post.
        form = PostForm(instance=post)
    else:
        # POST data submitted, process data:
        form = PostForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blog:post-detail', post.pk, post.slug)

    context = {'form': form}
    return render(request, 'blog/edit_post.html', context)

# Delete a post
class BlogPostDelete(LoginRequiredMixin, DeleteView):
    login_url = 'accounts:login'
    model = BlogPost
    success_url = reverse_lazy('blog:index')
    template_name = 'blog/delete_post.html'

blog/templates/blog/base_generic.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> 
    <title>Welcome to MicroBlog</title>
  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}
  {% bootstrap_messages %}
 <style>
  .fakeimg {
    height: 200px;
    background: #aaa;
  }
  body { padding-top: 40px; }
  </style>
</head>
{% buttons %}
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
<div class="container">
  <a class="navbar-brand" href="{% url 'blog:index' %}">MicroBlog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:posts' %}">All Posts</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:bloggers' %}">All Bloggers</a>
      </li>
    </ul>
    <ul class="navbar-nav justify-content-end ml-auto">
        {% if user.is_anonymous %}
        <li class="nav-item">
            <a class="btn btn-outline-primary btn-sm mr-sm-2" href="{% url 'accounts:register' %}?next={{ request.get_full_path|urlencode }}">Sign Up</a>
        </li>
        <li class="nav-item">
            <a class="btn btn-outline-primary btn-sm" href="{% url 'accounts:login' %}?next={{ request.get_full_path|urlencode }}">Login</a>
        </li>
        {% endif %}
        {% if user.is_authenticated %}
        <li class="nav-item">
            <a class="btn btn-outline-success btn-sm mr-sm-2" href="{% url 'blog:new-post' %}">New Post</a>
        </li>
        <li class="nav-item">
            <a class="btn btn-outline-danger btn-sm" href="{% url 'accounts:logout' %}">Logout</a> 
        </li>
        {% endif %}
    </ul>
  </div> 
  </div> 
</nav>
{% endbuttons %}
<body>
    {% block jumbotron %}
    {% endblock jumbotron %}

<div class="container" style="margin-top:30px">
    <div class="row">
    <div class="col-sm-4 border d-none d-md-block">
    {% if user.is_authenticated %}
    <h2>Welcome, {{ request.user.first_name }}</h2>
      <div class="card bg-light">
        <img class="card-img-top" src="https://www.w3schools.com/bootstrap4/img_avatar3.png">
        <div class="card-body">
            <h4 class="card-title">{{ request.user.first_name }} {{ request.user.last_name }}</h4>
            <a class="btn btn-primary" href="{% url 'blog:blogger-detail' request.user.username %}">Your Profile</a>
        </div>
      </div>
    {% endif %}
      <h3>Recent Posts</h3>
      <ul class="nav nav-pills flex-column">
        {% for post in sidebar_posts %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:post-detail' post.pk post.slug %}">{{ post.title }}{% if post.is_new %} <span class="badge badge-pill badge-secondary">New</span>{% endif %}</a>
        </li>
        {% endfor %}
      </ul>
      <hr class="d-sm-none">
    </div>
    <div class="col-sm-8">
    {% block content %}
    {% endblock content %}
    {% block pagination %}
        {% if is_paginated %}
            <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="{{ request.path }}?page={{ page_obj.previous_page_number }}">&laquo; Previous</a></li>
                        <li class="page-item"><a class="page-link" href="{{ request.path }}?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number}}</a></li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link" href="#">&laquo; Previous</a></li>
                    {% endif %}
                        <li class="page-item active"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
                    {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link" href="{{ request.path }}?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
                        <li class="page-item"><a class="page-link" href="{{ request.path }}?page={{ page_obj.next_page_number }}">Next &raquo;</a>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link" href="#">Next &raquo;</a></li>
                    {% endif %}
            </ul>
        {% endif %}
      {% endblock %}
    </div>
</div></div>
<div class="jumbotron text-center" style="margin-bottom:0; margin-top:30px">
{% block footer %}
  <p><a href="https://github.com/jordandelaney/microblog" taget="_blank">GitHub Repo</a></p>
{% endblock footer %}
</div>
</html>

blog/templates/blog/blogger_detail.html
{% extends 'blog/base_generic.html' %}

{% block content %}
<h1>Blogger: {{ blogger.first_name }} {{ blogger.last_name }}</h1>
<div class="card mb-2">
	<h5 class="card-header">About Me</h5>
	<div class="card-body">
		<p class="card-text">{% if blogger.biography %} {{ blogger.biography|linebreaks }} {% else %} <em>Coming Soon</em>{% endif %}</p>
		<a href="mailto:{{ blogger.email }}" class="btn btn-primary">Contact Me</a>
	</div>
</div>
<div class="card mb-2">
	<h5 class="card-header">My Recent Posts</h5>
	<div class="card-body">
		{% if posts %}
			<ul class="list-group">
    		{% for post in posts %}
        		<li class="list-group-item d-flex justify-content-between align-items-center"><a href="{% url 'blog:post-detail' post.pk post.slug %}">{{ post.title }}{% if post.is_new %} <span class="badge badge-pill badge-secondary">New</span>{% endif %}</a><span>{{ post.date_added|date:'F j, Y' }}</span></li>
    		{% endfor %}
    		</ul>
		{% else %}
    		<p class="card-text">No post history.</p>
		{% endif %}
	</div>
</div>
{% endblock %}

blog/templates/blog/blogpost_list.html
{% extends 'blog/base_generic.html' %}

{% block content %}
<h1>All posts</h1>
{% if blogpost_list %}
    {% for post in blogpost_list %}
            <div class="shadow p-4 mb-4 bg-white">
            	<a href="{% url 'blog:post-detail' post.pk post.slug %}"><h3>{{ post.title }}{% if post.is_new %} <span class="badge badge-pill badge-secondary">New</span></h3>{% endif %}</a></h3>
            	<h5><small class="text-muted"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-clock-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  				<path fill-rule="evenodd" d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8 3.5a.5.5 0 0 0-1 0V9a.5.5 0 0 0 .252.434l3.5 2a.5.5 0 0 0 .496-.868L8 8.71V3.5z"/>
				</svg> Posted By: <a href="{% url 'blog:blogger-detail' post.blogger.username %}">{{ post.blogger.first_name }} {{ post.blogger.last_name }}</a> on {{ post.date_added|date:"F jS, Y" }}</small></h5>
				<hr>
            	<p>{{ post.content|safe }}</p>
            	{% if user.is_anonymous %}
            	<a class="btn btn-sm btn-primary" href="{% url 'blog:post-detail' post.pk post.slug %}#comments">View Comments ({{ post.comment_set.count }})</a>
            	{% endif %}
            	{% if user.is_authenticated %}
            	<div class="btn group btn-group-sm" role="group">
            		<a class="btn btn-primary" href="{% url 'blog:post-detail' post.pk post.slug %}#comments">View Comments ({{ post.comment_set.count }})</a> 
            			<a class="btn btn-primary" href="{% url 'blog:post-detail' post.pk post.slug %}#add_comment">Add a Comment</a>
            			{% if request.user == post.blogger %}
            				<div class="btn-group btn-group-sm" role="group">
            				<button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown">Controls</button>
            				<div class="dropdown-menu">
            				<a class="dropdown-item" href="{% url 'blog:edit-post' post.pk %}">Edit Post</a> <a class="dropdown-item" href="{% url 'blog:delete-post' post.pk %}">Delete Post</a>
            				</div>
            		</div>
            			{% endif %}
                    </div>
            {% endif %}
            </div>
    {% endfor %}
{% else %}
    <p>There are no posts yet.</p>
{% endif %}
{% endblock content %}

blog/templates/blog/customuser_list.html
{% extends 'blog/base_generic.html' %}

{% block content %}
<h1>List of all Bloggers</h1>
<ul>
{% if customuser_list %}
<div class="container">
  <h2>Hover Rows</h2>
  <p>The .table-hover class enables a hover state (grey background on mouse over) on table rows:</p>            
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Firstname</th>
        <th>Lastname</th>
        <th>Username</th>
      </tr>
    </thead>
    <tbody>
    {% for blogger in customuser_list %}
      <tr>
        <td>{{ blogger.first_name }}</td>
        <td>{{ blogger.last_name }}</td>
        <td><a href="{% url 'blog:blogger-detail' post.blogger.username %}">{{ blogger.username }}</a></td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% else %
    <p>There are no bloggers, yet.</p>
{% endif %}
{% endblock content %}

blog/templates/blog/delete_post.html
{% extends "blog/base_generic.html" %}

{% block content %}

<h1>Delete Post: {{ blogpost.title }}</h1>
<div class="alert alert-danger">
  <strong>Warning!</strong> This action cannot be reversed. Your post will be permanently deleted.
</div>

<form action="" method="POST">
    {% csrf_token %}
        <button name="submit" class="btn btn-danger">Delete</button>
        <input type="hidden" name="next" value="/">
</form>

{% endblock %}

blog/templates/blog/edit_post.html
{% extends "blog/base_generic.html" %}
{% load bootstrap4 %}
{% block content %}
<h1>Edit Post: {{ blogpost.title }}</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.media }}
        {% bootstrap_form form %}
        <button name="submit" class="btn btn-primary">Submit</button>
        <input type="hidden" name="next" value="/">
    </form>
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base_generic.html' %}
{% block jumbotron %}
<div class="jumbotron text-center" style="margin-bottom:0">
  <a href="{% url 'blog:index' %}"><h1>MicroBlog</h1></a>
  <p>Welcome to MicroBlog. A small blog coded in Django's python framework.</p> 
</div>
{% endblock jumbotron %}
{% block content %}
<h1>Random Post</h1>
<div class="shadow p-4 mb-4 bg-white">
<a href="{% url 'blog:post-detail' post.pk post.slug %}"><h3>{{ post.title }}{% if post.is_new %} <span class="badge badge-pill badge-secondary">New</span></h3>{% endif %}</a></h3>
            	<h5><small class="text-muted"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-clock-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  				<path fill-rule="evenodd" d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8 3.5a.5.5 0 0 0-1 0V9a.5.5 0 0 0 .252.434l3.5 2a.5.5 0 0 0 .496-.868L8 8.71V3.5z"/>
				</svg> Posted By: <a href="{% url 'blog:blogger-detail' post.blogger.username %}">{{ post.blogger.first_name }} {{ post.blogger.last_name }}</a> on {{ post.date_added|date:"F jS, Y" }}</small></h5>
				<hr>
            	<p>{{ post.content|safe }}</p>
            {% if user.is_anonymous %}
            	<a class="btn btn-sm btn-primary" href="{% url 'blog:post-detail' post.pk post.slug %}">View Comments ({{ post.comment_set.count }})</a>
            </div>
            	{% endif %}
            	{% if user.is_authenticated %}
            	<div class="btn group btn-group-sm" role="group">
            		<a class="btn btn-primary" href="{% url 'blog:post-detail' post.pk post.slug %}">View Comments ({{ post.comment_set.count }})</a> 
            			<a class="btn btn-primary" href="{% url 'blog:post-detail' post.pk post.slug %}">Add a Comment</a>
            			{% if request.user == post.blogger %}
            				<div class="btn-group btn-group-sm" role="group">
            				<button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown">Controls</button>
            				<div class="dropdown-menu">
            				<a class="dropdown-item" href="{% url 'blog:edit-post' post.pk %}">Edit Post</a> <a class="dropdown-item" href="{% url 'blog:delete-post' post.pk %}">Delete Post</a>
            				</div>
            		</div>
            			{% endif %}
            	</div>
            </div>
            {% endif %}
</div>
{% endblock content %}

blog/templates/blog/new_post.html
{% extends 'blog/base_generic.html' %}
{% load bootstrap4 %}
{% block content %}
    <h2>Add a New Post</h2>

    <form action="{% url 'blog:new-post' %}" method='post'>
        {% csrf_token %}
        {{ form.media }}
        {% bootstrap_form form %}
        <button name="submit" class="btn btn-primary">Submit</button>
        <input type="hidden" name="next" value="/">
    </form>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends 'blog/base_generic.html' %}
{% load bootstrap4 %}
{% block content %}
<div class="shadow p-4 mb-4 bg-white">
<a href="{% url 'blog:post-detail' post.pk post.slug %}"><h3>{{ post.title }}{% if post.is_new %} <span class="badge badge-pill badge-secondary">New</span></h3>{% endif %}</a>
                <h5><small class="text-muted"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-clock-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8 3.5a.5.5 0 0 0-1 0V9a.5.5 0 0 0 .252.434l3.5 2a.5.5 0 0 0 .496-.868L8 8.71V3.5z"/>
                </svg> Posted By: <a href="{% url 'blog:blogger-detail' post.blogger.username %}">{{ post.blogger.first_name }} {{ post.blogger.last_name }}</a> on {{ post.date_added|date:"F jS, Y" }}</small></h5>
                <hr>
                <p>{{ post.content|safe }}</p>
                {% if user.is_anonymous %}
                <a class="btn btn-sm btn-primary" href="{% url 'blog:post-detail' post.pk post.slug %}#comments">View Comments ({{ post.comment_set.count }})</a>
                {% endif %}
{% if user.is_authenticated %}
                <div class="btn group btn-group-sm" role="group">
                    <a class="btn btn-primary" href="#comments">View Comments ({{ post.comment_set.count }})</a> 
                        <a class="btn btn-primary" href="#add_comment">Add a Comment</a>
                        {% if request.user == post.blogger %}
                            <div class="btn-group btn-group-sm" role="group">
                            <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown">Controls</button>
                            <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'blog:edit-post' post.pk %}">Edit Post</a> <a class="dropdown-item" href="{% url 'blog:delete-post' post.pk %}">Delete Post</a>
                            </div>
                    </div>
                        {% endif %}
                </div>
            {% endif %}
<h2 id="comments">Comments ({{ post.comment_set.count }})</h2>
{% if comments %}
{% for comment in comments %}
<div class="media border p-3 mt-3">
  <img src="https://www.w3schools.com/bootstrap4/img_avatar3.png" alt="{{ comment.owner.username }}" class="mr-3 mt-3 rounded-circle" style="width:60px;">
  <div class="media-body">
    <a href="{% url 'blog:blogger-detail' comment.owner.username %}"><h4>{{ comment.owner.first_name }} {{ comment.owner.last_name }}</a> <small><i>Posted on {{ comment.date_added|date:"F j, Y" }}</i></small></h4>
    <p>{{ comment.comment }}</p>
  </div>
</div>
{% endfor %}
<br>
    {% if comments.has_other_pages %}
        <ul class="pagination">
                {% if comments.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page={{ comments.previous_page_number }}">&laquo; Previous</a></li>
                {% else %}
                    <li class="page-item disabled"><a class="page-link" href="#">&laquo; Previous</a></li>
                {% endif %}
            {% for i in comments.paginator.page_range %}
                {% if comments.number == i %}
                    <li class="page-item active"><a class="page-link" href="?page={{ comments.current_page_number }}">{{ i }}</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if comments.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ comments.next_page_number }}">Next &raquo;</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link" href="#">Next &raquo;</a></li>
            {% endif %}
            </ul>
        {% endif %}
{% else %}
    <p>No comments have been added, yet.</p>
{% endif %}
{% if user.is_authenticated %}
<div id="accordion">
    <div class="card" id="add_comment">
    <div class="card-header">
      <a class="card-link" data-toggle="collapse" href="#collapseOne">
        Add a Comment
      </a>
    </div>
    <div id="collapseOne" class="collapse show" data-parent="#accordion">
      <div class="card-body">
        <form action="{% url 'blog:new-comment' post.pk %}" method='post'>
        {% csrf_token %}
        {% bootstrap_form form %}
        <button name="submit" class="btn btn-primary">Add Comment</button>
        <input type="hidden" name="next" value="/">
        </form>
      </div>
    </div>
  </div>
</div>
</div>
{% endif %}
{% endblock %}